// Parses an uploaded DOCX review file back into an updated SRT.
// Uses the mammoth library which extracts tables as HTML, then we parse out
// segment numbers, timestamps, and the translated text.

import mammoth from 'mammoth';
import { IncomingForm } from 'formidable';
import fs from 'fs';

export const config = { api: { bodyParser: false } };

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const form = new IncomingForm();
    const [fields, files] = await new Promise((resolve, reject) => {
      form.parse(req, (err, fields, files) => err ? reject(err) : resolve([fields, files]));
    });

    const file = Array.isArray(files.file) ? files.file[0] : files.file;
    if (!file) return res.status(400).json({ error: 'No file uploaded' });

    const buffer = fs.readFileSync(file.filepath);

    // Convert DOCX to HTML so we can read tables
    const result = await mammoth.convertToHtml({ buffer });
    const html = result.value;

    // Extract segments from the HTML
    // Each row of the translation table looks like:
    // <tr><td>1</td><td>00:00:00,000 --> 00:00:05,000</td><td>Arabic</td><td>Translation</td></tr>
    const segments = parseTableRows(html);

    if (segments.length === 0) {
      return res.status(400).json({
        error: 'Could not find translation table in the document. Make sure you uploaded a review document generated by this tool.'
      });
    }

    // Rebuild SRT
    const srt = segments.map((seg, i) =>
      `${i + 1}\n${seg.timestamp}\n${seg.text}`
    ).join('\n\n') + '\n';

    return res.status(200).json({
      srtContent: srt,
      segmentCount: segments.length
    });
  } catch (e) {
    return res.status(500).json({ error: e.message });
  }
}

function parseTableRows(html) {
  const segments = [];
  // Match table rows
  const trRegex = /<tr>([\s\S]*?)<\/tr>/g;
  let trMatch;
  while ((trMatch = trRegex.exec(html)) !== null) {
    const row = trMatch[1];
    const cells = [];
    const tdRegex = /<td[^>]*>([\s\S]*?)<\/td>/g;
    let tdMatch;
    while ((tdMatch = tdRegex.exec(row)) !== null) {
      cells.push(stripHtml(tdMatch[1]).trim());
    }
    // We expect 4 columns: #, timestamp, Arabic original, translation
    if (cells.length >= 4) {
      const segNum = cells[0];
      const timestamp = cells[1];
      const translation = cells[3];
      // Validate this looks like a real segment row (number + timestamp pattern)
      if (/^\d+$/.test(segNum) && /\d{2}:\d{2}:\d{2}/.test(timestamp) && translation) {
        segments.push({ timestamp, text: translation });
      }
    }
  }
  return segments;
}

function stripHtml(html) {
  return html
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/p>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/\s+/g, ' ')
    .trim();
}
