import { getYouTubeAccessToken } from './_youtube-auth';

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { videoUrl } = req.body;
  if (!videoUrl) return res.status(400).json({ error: 'Missing videoUrl' });

  const videoId = extractVideoId(videoUrl);
  if (!videoId) return res.status(400).json({ error: 'Could not extract video ID from URL' });

  try {
    const accessToken = await getYouTubeAccessToken();

    // Step 1 — list caption tracks for this video via authenticated API
    const listRes = await fetch(
      `https://www.googleapis.com/youtube/v3/captions?part=snippet&videoId=${videoId}`,
      { headers: { Authorization: `Bearer ${accessToken}` } }
    );

    if (!listRes.ok) {
      const err = await listRes.json().catch(() => ({}));
      return res.status(listRes.status).json({
        error: err?.error?.message || `Failed to list captions (HTTP ${listRes.status})`,
        hint: 'Make sure your account has access to this video, or that the video has captions.'
      });
    }

    const listData = await listRes.json();
    if (!listData.items || listData.items.length === 0) {
      return res.status(404).json({
        error: 'This video has no caption tracks at all. Add captions in YouTube Studio first, then try again.'
      });
    }

    // Find Arabic track — prefer manually-uploaded, fall back to auto-generated
    const arabicTracks = listData.items.filter(t => t.snippet.language === 'ar');
    if (arabicTracks.length === 0) {
      const available = listData.items.map(t => t.snippet.language).join(', ');
      return res.status(404).json({
        error: `No Arabic caption track found on this video. Available languages: ${available || 'none'}`
      });
    }

    // Prefer manual track over ASR (auto-generated)
    const arabicTrack = arabicTracks.find(t => t.snippet.trackKind !== 'asr') || arabicTracks[0];

    // Step 2 — download the caption track in SRT format
    const downloadRes = await fetch(
      `https://www.googleapis.com/youtube/v3/captions/${arabicTrack.id}?tfmt=srt`,
      { headers: { Authorization: `Bearer ${accessToken}` } }
    );

    if (!downloadRes.ok) {
      const errText = await downloadRes.text().catch(() => '');
      return res.status(downloadRes.status).json({
        error: 'Could not download the caption file. The video owner may have disabled third-party caption access.',
        details: errText.slice(0, 200)
      });
    }

    const srtContent = await downloadRes.text();
    if (!srtContent || srtContent.trim().length < 10) {
      return res.status(404).json({ error: 'Caption file was empty.' });
    }

    return res.status(200).json({
      srtContent,
      videoId,
      trackKind: arabicTrack.snippet.trackKind || 'standard',
      isAutoGenerated: arabicTrack.snippet.trackKind === 'asr'
    });
  } catch (error) {
    return res.status(500).json({ error: error.message });
  }
}

function extractVideoId(input) {
  if (!input) return null;
  const trimmed = input.trim();
  if (/^[A-Za-z0-9_-]{11}$/.test(trimmed)) return trimmed;
  let match = trimmed.match(/[?&]v=([A-Za-z0-9_-]{11})/);
  if (match) return match[1];
  match = trimmed.match(/youtu\.be\/([A-Za-z0-9_-]{11})/);
  if (match) return match[1];
  match = trimmed.match(/youtube\.com\/embed\/([A-Za-z0-9_-]{11})/);
  if (match) return match[1];
  match = trimmed.match(/youtube\.com\/shorts\/([A-Za-z0-9_-]{11})/);
  if (match) return match[1];
  return null;
}
